version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - './frontend/node_modules:/app/node_modules'
    ports:
      - '8081:8080'

